name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2015-02-25
version: '8.0.0-beta7'
core: '8.x'
project: 'drupal'
datestamp: 1424875577
